#! /bin/bash

old_suffix=$1
new_suffix=$2

if (( $# != 2 ))
then
    echo "An improper number of arguments are given.">&2
    exit 1
fi

for f in *.$old_suffix
do
	new_name=${f%.*}.$new_suffix
	#check if the new file name exist
	if [[ -e $new_name ]]
	then 
	        echo "File name is exist">&2
		exit 2
	fi
	echo Rename $f to $new_name
	mv $f $new_name
	if(( $? != 0 ))
	then
	    echo "File can not be renamed.">&2
	    exit 3
        fi	
done
exit 0
